import Head from 'next/head'
import styles from '../styles/Home.module.css'

import ShowMorePosts from './components/showMorePosts'
import DisplayPost from './components/displayPost'

const blogPosts = [
  {
    type: 'article',
    author: 'piotr żelazny',
    publishDate: '1 godz. temu',
    title: `Poprzednia dekada należała do Drake'a. Jak Kanadyjczyk wpłynął na muzykę popularną?`,
    genre: 'Hip-Hop'
  },
  {
    type: 'podcast',
    author: 'Rozmowy: Wojewódzki & Kędzierski',
    title: 'Bodnar: Jakim samochodem jeździ rzecznik'
  },
  {
    type: 'article',
    author: 'piotr żelazny',
    publishDate: '1 godz. temu',
    title: `Poprzednia dekada należała do Drake'a. Jak Kanadyjczyk wpłynął na muzykę popularną?`,
    genre: 'Hip-Hop'
  },
  {
    type: 'article',
    author: 'piotr żelazny',
    publishDate: '1 godz. temu',
    title: `Poprzednia dekada należała do Drake'a. Jak Kanadyjczyk wpłynął na muzykę popularną?`,
    genre: 'Hip-Hop'
  },
  {
    type: 'podcast',
    author: 'Rozmowy: Wojewódzki & Kędzierski',
    title: 'Bodnar: Jakim samochodem jeździ rzecznik'
  },
  {
    type: 'article',
    author: 'piotr żelazny',
    publishDate: '1 godz. temu',
    title: `Poprzednia dekada należała do Drake'a. Jak Kanadyjczyk wpłynął na muzykę popularną?`,
    genre: 'Hip-Hop'
  },
  {
    type: 'podcast',
    author: 'Rozmowy: Wojewódzki & Kędzierski',
    title: 'Bodnar: Jakim samochodem jeździ rzecznik'
  }
]

export default function Home() {

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
          { blogPosts.map((post, i) => <DisplayPost key={i} data={post}/>) }
          <ShowMorePosts />
      </main>
    </div>
  )
}
